# application.properties
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.exposed-headers=access-control-allow-origin
quarkus.http.cors.access-control-allow-credentials=true
morapack.upload.dir=${env.MORAPACK_UPLOAD_DIR:uploads}
